version: "3"
services:
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - ./redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]
    stan:
        image: nats-streaming:latest
        ports:
            - 4222:4222
            - 8222:8222
        command: [ "-p", "4222", "-m", "8222", "-cid", "cluster" ]
